###############################################
#                                             #
#      DonatorExpress Inventory Config        #
#                                             #
###############################################

# Simple, should the command /donate inv be enabled?

inventoryEnable: true

# This MUST only be set to 9, 18, or 27

inventorySize: 9

# Pick a name for the inventory. This is shown at the top

inventoryName: "DonatorExpress"

invSlot1:
    # Enter in the title
    # If you don't want anything to be in this slot, make title: 'null'
    title: '&4Package Name '
    # Enter in the description
    description: 
        - '&4This package gives you blah blah blah '
        - '&4It also gives you this this and this '
    # Must be in 
    block: ' '
    # How many of those blocks should be 
    stackNumber: 1
    # What command should be executed when clicked on? Excluding the /
    command: 'donate buy [packageName]'
    
invSlot2:
    title: ' '
    description:
        - ' '
        - ' '
    block: ' '
    stackNumber: 1
    command: ' '

invSlot3:
    title: ' '
    description:
        - ' '
        - ' '
    block: ' '
    stackNumber: 1
    command: ' '
    
invSlot4:
    title: ' '
    description:
        - ' '
        - ' '
    block: ' '
    stackNumber: 1
    command: ' '
    
invSlot5:
    title: ' '
    description:
        - ' '
        - ' '
    block: ' '
    stackNumber: 1
    command: ' '
    
invSlot6:
    title: ' '
    description:
        - ' '
        - ' ' 
    block: ' '
    stackNumber: 1
    command: ' '
    
invSlot7:
    title: ' '
    description:
        - ' '
        - ' ' 
    block: ' '
    stackNumber: 1
    command: ' '
    
invSlot8:
    title: ' '
    description:
        - ' '
        - ' '
    block: ' '
    stackNumber: 1
    command: ' '
    
invSlot9:
    title: ' '
    description:
        - ' '
        - ' ' 
    block: ' '
    stackNumber: 1
    command: ' '
    
# And so on and so on until a max of 27