name: DonatorExpress
main: net.targetcraft.donatorexpress.Main
version: 1.6.6
description: DonatorExpress
website: http://aman207.net/wiki
author: aman207
authors: [AzroWear] 
softdepend: [Vault]

commands:
    donate:
     description: General command for all of DonatorExpress's needs
     aliases: [donator, rank, buy, package]
permissions:
    donexpress.*:
        description: Gives access to all commands
        children:
            donexpress.admin.*: true
            donexpress.user: true
    donexpress.admin.*:
        description: Access to all admin commands
        default: op
        children:
            donexpress.admin.edit: true
            donexpress.admin.checkvc: true
            donexpress.admin.add: true
            donexpress.admin.delete: true
            donexpress.admin.addvc: true
            donexpress.admin.removevc: true
            donexpress.admin.reload: true
            donexpress.admin.setvc: true
            donexpress.admin.recent: true
            donexpress.admin.update: true
            donexpress.admin.signremove: true
            donexpress.admin.signplace: true
            donexpress.user: true
    donexpress.admin.basic:
        description: Basic access to admin commands. Gives checkvc and update notifications
        default: op
        children:
            donexpress.admin.checkvc: true
            donexpress.admin.update: true
    donexpress.admin.add:
        description: Adds a rank to the config
        default: op
    donexpress.admin.delete:
        description: Deletes a rank from the config
        default: op
    donexpress.admin.checkvc:
        description: Checks the amount of virtual currency that a player has
        default: op
    donexpress.admin.checkp:
        description: 
        default:
    donexpress.admin.addvc:
        description: Adds virtual currency to a specified user
        default: op
    donexpress.admin.removevc:
        description: Removes virtual currency from a user
        default: op
    donexpress.admin.reload:
        description: Reloads the config
        default: op
    donexpress.admin.setvc:
        description: Sets the amount of vc for a user. Not add
        default: op
    donexpress.admin.recent:
        description: Lets the player see the 5 most recent transactions
        default: op
    donexpress.admin.update:
        description: Notifies the user about an update
        default: op
    donexpress.admin.signplace:
        description: Allows a sign with [DE] as the first line to be placed
        default: op
    donexpress.admin.signremove:
        description: Allows a sign with [DE] as the first line to be destroyed
        default: op
    donexpress.user:
        description: Any commands that a user would use
        default: op
